<?php
  define('TITRE_ACCUEIL', "Ma page d'accueil");
  define('DESCRIP_LOGO', "Logo de mon site");
  define('PRESENTATION_ACCUEIL', "Bienvenue sur le site de test de Mathieu Chorier");
  define('ERREUR_404', "Erreur 404");
  define('TITRE_ERREUR', "OUPS la page n'existe pas");
  define('LABEL_IDENTIFIANT', "Identifiant");
  define('LABEL_PASSWORD', "Mot de passe");
  define('BOUTON_CONNEXION', "Connexion");
  define('BOUTON_DECONNEXION', "Deconnexion");
  define('MESSAGE_CONNECTE', "Vous êtes connecté");
  define('MESSAGE_DECONNECTE', "Vous êtes déconnecté");
  define('MESSAGE_PASSWORD_INVALIDE', "Votre mot de passe est incorrect");
  define('MESSAGE_IMAGE_MODIFIEE', "Votre image a bien été modifiée");
  define('MESSAGE_IMAGE_SUPPRIMEE', "Votre image a bien été supprimée");
  define('MESSAGE_IMAGE_AJOUTEE', "Votre image a bien été ajoutée");
  define('MESSAGE_IMAGE_DEJA_EXISTANTE', "Votre image existe déjà");
  define('MESSAGE_ORDRE_DEJA_UTILISE', "Vous ne pouvez pas choisir un ordre déjà défini");
  define('MESSAGE_TAILLE_TROP_GRANDE', "Taille de l'image trop grande");
  define('MESSAGE_MAUVAIS_FORMAT', "Mauvais format d'image");
